#!/bin/sh
#
# Runs at the end of git flow release finish
#
# Positional arguments:
# $1    The version (including the version prefix)
# $2    The origin remote
# $3    The full branch name (including the release prefix)
#
set -e

VERSION=$1
ORIGIN=$2
BRANCH=$3

if [ $? -ne 0 ]; then
    exit 1
fi

exit 0
